services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - /Users/alghisi/WebstormProjects/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    restart: always

  nextjs-app:
    container_name: nextjs-dev
    build:
      context: .
      dockerfile: DockerfileDev
    ports:
      - 3000:3000
    env_file:
      - ./.env.local
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Forza il file watcher a rilevare i cambiamenti in Docker
      - WATCHPACK_POLLING=true
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "pnpm run db:migrate-dev || true && pnpm run dev"]
