services:

  nextjs-app:
    container_name: amservice
    image: lalghisi/amservice
    volumes:
      - /opt/manutenzione/private-files/:/app/private-files/
      - /opt/manutenzione/:/app/source/
      - shared-volume:/tmp/tempAmService
    ports:
      - 80:3000
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: always
    networks:
      - amservice-network
    env_file:
      - stack.env

  migrator:
    image: lalghisi/migrator:latest
    container_name: migrator
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - amservice-network
    env_file:
      - stack.env
    
  cronjob:
    image: lalghisi/cron:1.0
    container_name: cronjob_amservice
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: always
    networks:
      - amservice-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchover
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600 --label-enable
    restart: always


  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - /opt/manutenzione/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    restart: always
    networks:
      - amservice-network
    
  root-shell:
    container_name: root-shell
    image: alpine:latest
    user: root  
    volumes:
      - /opt/manutenzione/:/app/source/
      - shared-volume:/backups
    stdin_open: true  #
    tty: true 
    restart: "no"
    networks:
      - amservice-network
      
  db-recovery:
    container_name: db-recovery
    volumes:
      - shared-volume:/backups
    image: lalghisi/dbrecover
    networks:
      - amservice-network
    env_file:
      - stack.env
    
networks:
  amservice-network:
    driver: bridge


volumes:
  shared-volume:
    driver: local
  next_cache:
    driver: local