version: '3'

services:
  nextjs-app:
    image: lalghisi/amservice:1.0
    volumes:
      - ./:/usr/features/app
      - /opt/manutenzione/private-files/:/usr/features/app/app/lib/params/
    ports:
      - 3000:3000
    env_file:
        - ./.env.local
    container_name: nextjs-app
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600 --label-enable
    restart: always

  cronjob:
    image: lalghisi/cron:1.0
    container_name: cronjob
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: always