import { Inter } from "next/font/google";
import "./globals.css";
import {ContextApiProvider} from "./Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "AM Service",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
        <html lang="en">
        <body className={inter.className} data-theme="dark">
        <ContextApiProvider>{children}</ContextApiProvider>
        </body>
        </html>
    );
}
