import { Inter } from "next/font/google";
import "./globals.css";
import "@ag-grid-community/styles/ag-grid.css";
import "@ag-grid-community/styles/ag-theme-quartz.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "AM Service",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
        <html lang="en">
        <body className={inter.className} data-theme="dark">
        </body>
        </html>
    );
}
