
import { RowClassParams } from "ag-grid-community";
import {RowData} from "@/src/client/types/types";

export const rowClassRules ={
    'row-ev-coin-in': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_COIN_IN',
    'row-ev-bnk-in': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_BNK_IN',
    'row-ev-pax-payment': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_PAX_PAYMENT',
    'row-ev-ing-payment': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_ING_PAYMENT',
    'row-ev-card-ciclo-ok-eta': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_CARD_CICLO_OK_ETA',
    'row-ev-ticket': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_TICKET',
    'row-ev-dev-sernum': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_DEV_SERNUM',
    'row-ev-dev-sernumchanged': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_DEV_SERNUMCHANGED',
    'row-ev-accensione': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_ACCENSIONE',
    'row-ev-producer-pressed': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_PRODUCT_PRESSED',
    'row-ev-wdogfired': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_WDOGFIRED',
    'row-ev-prod-venduto': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_PROD_VENDUTO',
    'row-ev-vendsession-end': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_VENDSESSION_END',
    'row-ev-usbl-noise': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_USBL_NOISE',
    'row-ev-usbl-nocom': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_USBL_NOCOM',
    'row-ev-usbl-nocomlong': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_USBL_NOCOMLONG',
    'row-ev-usbdev-detach': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_USBDEV_DETACH',
    'row-ev-bnk-escrow': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_BNK_ESCROW',
    'row-ev-v2-samebnk': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_V2_SAMEBNK',
    'row-ev-adimac-alarm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_ADIMAC_ALARM',
    'row-ev-prod-non-venduto': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_PROD_NON_VENDUTO',
    'row-ev-acc-restart': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_ACC_RESTART',
    'row-ev-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_NOCOMM',
    'row-ev-card-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_CARD_NOCOMM',
    'row-ev-bnk-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_BNK_NOCOMM',
    'row-ev-bnk-jammed': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_BNK_JAMMED',
    'row-ev-cac-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_CAC_NOCOMM',
    'row-ev-finger-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_FINGER_NOCOMM',
    'row-ev-c5-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_C5_NOCOMM',
    'row-ev-mot-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_MOT_NOCOMM',
    'row-ev-hop-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_HOP_NOCOMM',
    'row-ev-locker-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_LOCKER_NOCOMM',
    'row-ev-gv-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_GV_NOCOMM',
    'row-ev-prn-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_PRN_NOCOMM',
    'row-ev-frigo-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_FRIGO_NOCOMM',
    'row-ev-sanden-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_SANDEN_NOCOMM',
    'row-ev-ifsanden-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_IFSANDEN_NOCOMM',
    'row-ev-adimac-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_ADIMAC_NOCOMM',
    'row-ev-sileaff-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_SILEAFF_NOCOMM',
    'row-ev-pwm-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_PWM_NOCOMM',
    'row-ev-serled-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_SERLED_NOCOMM',
    'row-ev-prel-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_PREL_NOCOMM',
    'row-ev-cs-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_CS_NOCOMM',
    'row-ev-az-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_AZ_NOCOMM',
    'row-ev-qrb-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_QRB_NOCOMM',
    'row-ev-ing-nocomm': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_ING_NOCOMM',
    'row-ev-pax-error': (params: RowClassParams<RowData>) => params.data?.EventString === 'EV_PAX_ERROR',
};